language: node_js
node_js:
- '4.3'
sudo: false
env:
- L10N_LOCALE_SRC="locales" L10N_LOCALE_DEST="dist/locales"
cache:
  directories:
  - node_modules
  - locale
deploy:
  provider: heroku
  api_key:
    secure: E2houbiE3BVUltZqlMlaCIUOoAjecJTFVi/J5+TPGV04ZPitOXNs5NXsZ21nSBYRapTdUwDI3ulD54fgR50vlOnW/FWnC3NdSjqWrCJDpGzXnSYRzPFeAejs8DtNvIsBvjLoLDS8eK5L4tlW7swyiFV2huAXloqKNR6LnvEFzVQ=
  app: bramble-staging
  on:
    repo: mozilla/thimble.mozilla.org
    branch: master
